import mongoose from "mongoose";

const amazonSchema = mongoose.Schema(
  {
    amazon_id: { type: String, required: true },
    amazon_user: { type: String },
    amazon_password: { type: String },
    amazon_detail: { type: String },
    amazon_limit: { type: String,},
    amazon_item: { type: String },
    amazon_sold: { type: String },
    amazon_feedback: { type: String },
    amazon_plan: { type: String,default: "chrome"},
    amazon_processing: { type: String },
    amazon_type: { type: String },
    amazon_sell_status: { type: String },
    amazon_owner: { type: String },
    amazon_employee: { type: String, default: "Nguyễn Hoài" },
    amazon_outline: { type: String },
    amazon_status: { type: String },
    amazon_class: { type: String },
    amazon_support:{ type: String },
    amazon_note: { type: String },
    device_id: { type: String },
    info_id: { type: String },
    proxy_id:{ type: String },
    mail_id: { type: String },
    sim_id: { type: String },
    bank_id: { type: String },
    payoneer_id: { type: String },
    paypal_id: { type: String },
    pingpong_id: { type: String },
    ebay_id: { type: String },
    etsy_id: { type: String },
    amazon_id: { type: String },
    shopee_id: { type: String },
    facebook_id: { type: String },
    tiktok_id: { type: String },
    list_view: { type: String },
    amazon_image_url: { type: String },
    // List date
    amazondate_delivery:{ type: String },
    amazondate_start: { type: String },
    amazondate_nextclass: { type: String },
    amazondate_verify: { type: String },
    amazondate_seller: { type: String },
    amazondate_verifybank: { type: String },
    amazondate_draft: { type: String },
    amazondate_list1: { type: String },
    amazondate_list2: { type: String },
    amazondate_list3: { type: String },
    amazondate_list4: { type: String },
    amazondate_list5: { type: String },
    amazondate_expectedseller: { type: String },
    amazondate_expectedlist1: { type: String },
    amazondate_expectedlist2: { type: String },
    amazondate_expectedlist3: { type: String },
    amazondate_expectedlist4: { type: String },
    amazondate_expectedlist5: { type: String },
    amazondate_suspended: { type: String },
    amazondate_checksus1: { type: String },
    amazondate_contact1: { type: String },
    amazondate_contact2: { type: String },
    amazondate_contact3: { type: String },
    amazondate_contact4: { type: String },
    amazondate_contact5: { type: String },
    amazondate_checksus2: { type: String },
    amazondate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Amazon", amazonSchema);
