import mongoose from "mongoose";
import Sim from "../models/sim";
const { ObjectId } = mongoose.Schema;

const bankSchema = mongoose.Schema(
  {
    bank_id: { type: String, required: true },
    bank_user: { type: String },
    bank_password: { type: String },
    bank_detail: { type: String },
    bank_limit: { type: String },
    bank_item: { type: String },
    bank_sold: { type: String },
    bank_feedback: { type: String },
    bank_plan: { type: String },
    bank_block: { type: String },
    bank_error: { type: String },
    bank_processing: { type: String },
    bank_type: { type: String },
    bank_sell_status: { type: String },
    bank_owner: { type: String },
    bank_employee: { type: String },
    bank_outline: { type: String },
    bank_status: { type: String },
    bank_class: { type: String },
    bank_support: { type: String },
    bank_note: { type: String },
    //Liên kết field
    list_view: { type: String },
    device_id: { type: String, ref: "Device" },
    proxy_id:{ type: String, ref: "Proxy"},
    info_id: { type: String , ref: "Info"},

    mail_id: { type: ObjectId, ref: "Mail"},
    sim_id: { type: ObjectId, ref: "Sim" },
    //bank_id: { type: ObjectId, ref: "Bank" },
    payoneer_id: { type: ObjectId, ref: "Payoneer"},
    paypal_id: { type: ObjectId, ref: "Paypal" },
    pingpong_id: {type: ObjectId, ref: "Pingpong" },
    ebay_id: {type: ObjectId, ref: "Ebay" },
    etsy_id: { type: ObjectId, ref: "Etsy"},
    amazon_id: { type: ObjectId, ref: "Amazon"},
    shopee_id: { type: ObjectId, ref: "Shopee"},
    facebook_id: { type: ObjectId, ref: "Facebook"},
    tiktok_id: { type: ObjectId, ref: "Tiktok"},


    bank_image_url: { type: String },
    bank_history: { type: String },
    // List date
    bankdate_delivery: { type: String },
    bankdate_start: { type: String },
    bankdate_nextclass: { type: String },
    bankdate_verify: { type: String },
    bankdate_seller: { type: String },
    bankdate_verifybank: { type: String },
    bankdate_draft: { type: String },
    bankdate_list1: { type: String },
    bankdate_list2: { type: String },
    bankdate_list3: { type: String },
    bankdate_list4: { type: String },
    bankdate_list5: { type: String },
    bankdate_calendarseller: { type: String },
    bankdate_calendarlist1: { type: String },
    bankdate_calendarlist2: { type: String },
    bankdate_calendarlist3: { type: String },
    bankdate_calendarlist4: { type: String },
    bankdate_calendarlist5: { type: String },
    bankdate_moveroom: { type: String },
    bankdate_error: { type: String },
    bankdate_restrict: { type: String },
    bankdate_suspended: { type: String },
    bankdate_contact1: { type: String },
    bankdate_contact2: { type: String },
    bankdate_contact3: { type: String },
    bankdate_contact4: { type: String },
    bankdate_contact5: { type: String },
    bankdate_checksus1: { type: String },
    bankdate_checksus2: { type: String },
    bankdate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Bank", bankSchema);
