import mongoose from "mongoose";
const { ObjectId } = mongoose.Schema;

const billSchema = mongoose.Schema(
  {
    bill_id: { type: String, required: true },
    bill_date: { type: String },
    bill_type: { type: String },
    bill_action: { type: String },
    bill_owner: { type: String },
    bill_supplier: { type: String },
    bill_contact_phone: { type: String },
    bill_contact_social1: { type: String },
    bill_contact_social2: { type: String },
    bill_payment: { type: String },
    bill_debt: { type: String },
    bill_note: { type: String },
    bill_work: { type: String },
    bill_content: { type: String },
    bill_number: { type: String },
    bill_price: { type: String },
    bill_total: { type: String },
    bill_status: { type: String },
    bill_class: { type: String },
    bill_support: { type: String },
    bill_note: { type: String },
    //Liên kết field
    list_view: { type: String },
    device_id: { type: String, ref: "Device" },
    proxy_id:{ type: String, ref: "Proxy"},
    info_id: { type: String , ref: "Info"},

    mail_id: { type: ObjectId, ref: "Mail"},
    sim_id: { type: ObjectId, ref: "Sim" },
    //bill_id: { type: ObjectId, ref: "Bank" },
    payoneer_id: { type: ObjectId, ref: "Payoneer"},
    paypal_id: { type: ObjectId, ref: "Paypal" },
    pingpong_id: {type: ObjectId, ref: "Pingpong" },
    ebay_id: {type: ObjectId, ref: "Ebay" },
    etsy_id: { type: ObjectId, ref: "Etsy"},
    amazon_id: { type: ObjectId, ref: "Amazon"},
    shopee_id: { type: ObjectId, ref: "Shopee"},
    facebook_id: { type: ObjectId, ref: "Facebook"},
    tiktok_id: { type: ObjectId, ref: "Tiktok"},


    bill_image_url: { type: String },
    bill_history: { type: String },
    // List date
    billdate_delivery: { type: String },
    billdate_start: { type: String },
    billdate_nextclass: { type: String },
    billdate_verify: { type: String },
    billdate_seller: { type: String },
    billdate_verifybill: { type: String },
    billdate_draft: { type: String },
    billdate_list1: { type: String },
    billdate_list2: { type: String },
    billdate_list3: { type: String },
    billdate_list4: { type: String },
    billdate_list5: { type: String },
    billdate_calendarseller: { type: String },
    billdate_calendarlist1: { type: String },
    billdate_calendarlist2: { type: String },
    billdate_calendarlist3: { type: String },
    billdate_calendarlist4: { type: String },
    billdate_calendarlist5: { type: String },
    billdate_moveroom: { type: String },
    billdate_error: { type: String },
    billdate_restrict: { type: String },
    billdate_suspended: { type: String },
    billdate_contact1: { type: String },
    billdate_contact2: { type: String },
    billdate_contact3: { type: String },
    billdate_contact4: { type: String },
    billdate_contact5: { type: String },
    billdate_checksus1: { type: String },
    billdate_checksus2: { type: String },
    billdate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Bill", billSchema);
