import mongoose from "mongoose";

const deviceSchema = mongoose.Schema(
  {
    device_id: { type: String, required: true },
    device_user: { type: String },
    device_password: { type: String },
    device_detail: { type: String },
    device_limit: { type: String,},
    device_item: { type: String },
    device_sold: { type: String },
    device_feedback: { type: String },
    device_plan: { type: String,default: "chrome"},
    device_processing: { type: String },
    device_type: { type: String },
    device_sell_status: { type: String },
    device_owner: { type: String },
    device_employee: { type: String, default: "Nguyễn Hoài" },
    device_outline: { type: String },
    device_status: { type: String },
    device_class: { type: String },
    device_support:{ type: String },
    device_note: { type: String },
    device_id: { type: String },
    proxy_id:{ type: String },
    info_id: { type: String },
    mail_id: { type: String },
    sim_id: { type: String },
    bank_id: { type: String },
    payoneer_id: { type: String },
    paypal_id: { type: String },
    pingpong_id: { type: String },
    ebay_id: { type: String },
    etsy_id: { type: String },
    amazon_id: { type: String },
    shopee_id: { type: String },
    facebook_id: { type: String },
    tiktok_id: { type: String },
    list_view: { type: String },
    device_image_url: { type: String },
    // List date
    devicedate_delivery:{ type: String },
    devicedate_start: { type: String },
    devicedate_nextclass: { type: String },
    devicedate_verify: { type: String },
    devicedate_seller: { type: String },
    devicedate_verifybank: { type: String },
    devicedate_draft: { type: String },
    devicedate_list1: { type: String },
    devicedate_list2: { type: String },
    devicedate_list3: { type: String },
    devicedate_list4: { type: String },
    devicedate_list5: { type: String },
    devicedate_expectedseller: { type: String },
    devicedate_expectedlist1: { type: String },
    devicedate_expectedlist2: { type: String },
    devicedate_expectedlist3: { type: String },
    devicedate_expectedlist4: { type: String },
    devicedate_expectedlist5: { type: String },
    devicedate_suspended: { type: String },
    devicedate_checksus1: { type: String },
    devicedate_contact1: { type: String },
    devicedate_contact2: { type: String },
    devicedate_contact3: { type: String },
    devicedate_contact4: { type: String },
    devicedate_contact5: { type: String },
    devicedate_checksus2: { type: String },
    devicedate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Device", deviceSchema);
