import mongoose from "mongoose";
import Sim from "../models/sim";
const { ObjectId } = mongoose.Schema;

const deviceSchema = mongoose.Schema(
  {
    device_id: { type: String, required: true },
    device_user: { type: String },
    device_password: { type: String },
    device_detail: { type: String },
    device_limit: { type: String },
    device_item: { type: String },
    device_sold: { type: String },
    device_feedback: { type: String },
    device_plan: { type: String },
    device_block: { type: String },
    device_error: { type: String },
    device_processing: { type: String },
    device_type: { type: String },
    device_sell_status: { type: String },
    device_owner: { type: String },
    device_employee: { type: String },
    device_outline: { type: String },
    device_status: { type: String },
    device_class: { type: String },
    device_support: { type: String },
    device_note: { type: String },
    //Liên kết field
    list_view: { type: String },
    //device_id: { type: String, ref: "Device" },
    proxy_id:{ type: String, ref: "Proxy"},
    info_id: { type: String , ref: "Info"},
    mail_id: { type: ObjectId, ref: "Mail"},
    sim_id: { type: ObjectId, ref: "Sim" },
    bank_id: { type: ObjectId, ref: "Bank" },
    payoneer_id: { type: ObjectId, ref: "Payoneer"},
    paypal_id: { type: ObjectId, ref: "Paypal" },
    pingpong_id: {type: ObjectId, ref: "Pingpong" },
    ebay_id: {type: ObjectId, ref: "Ebay" },
    etsy_id: { type: ObjectId, ref: "Etsy"},
    amazon_id: { type: ObjectId, ref: "Amazon"},
    shopee_id: { type: ObjectId, ref: "Shopee"},
    facebook_id: { type: ObjectId, ref: "Facebook"},
    tiktok_id: { type: ObjectId, ref: "Tiktok"},


    device_image_url: { type: String },
    device_history: { type: String },
    // List date
    devicedate_delivery: { type: String },
    devicedate_start: { type: String },
    devicedate_nextclass: { type: String },
    devicedate_verify: { type: String },
    devicedate_seller: { type: String },
    devicedate_verifybank: { type: String },
    devicedate_draft: { type: String },
    devicedate_list1: { type: String },
    devicedate_list2: { type: String },
    devicedate_list3: { type: String },
    devicedate_list4: { type: String },
    devicedate_list5: { type: String },
    devicedate_calendarseller: { type: String },
    devicedate_calendarlist1: { type: String },
    devicedate_calendarlist2: { type: String },
    devicedate_calendarlist3: { type: String },
    devicedate_calendarlist4: { type: String },
    devicedate_calendarlist5: { type: String },
    devicedate_moveroom: { type: String },
    devicedate_error: { type: String },
    devicedate_restrict: { type: String },
    devicedate_suspended: { type: String },
    devicedate_contact1: { type: String },
    devicedate_contact2: { type: String },
    devicedate_contact3: { type: String },
    devicedate_contact4: { type: String },
    devicedate_contact5: { type: String },
    devicedate_checksus1: { type: String },
    devicedate_checksus2: { type: String },
    devicedate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Device", deviceSchema);
