import mongoose from "mongoose";
import Sim from "../models/sim";

const ebaySchema = mongoose.Schema(
  {
    ebay_id: { type: String, required: true },
    ebay_user: { type: String },
    ebay_password: { type: String },
    ebay_detail: { type: String },
    ebay_limit: { type: String,},
    ebay_item: { type: String },
    ebay_sold: { type: String },
    ebay_feedback: { type: String },
    ebay_plan: { type: String},
    ebay_block: { type: String},
    ebay_error: { type: String},
    ebay_processing: { type: String },
    ebay_type: { type: String },
    ebay_sell_status: { type: String },
    ebay_owner: { type: String },
    ebay_employee: { type: String },
    ebay_outline: { type: String },
    ebay_status: { type: String },
    ebay_class: { type: String },
    ebay_support:{ type: String },
    ebay_note: { type: String },
    device_id: { type: String },
    proxy_id:{ type: String },
    info_id: { type: String },
    mail_id: { type: String },
    sim_id: { type: String },
    bank_id: { type: String },
    payoneer_id: { type: String },
    paypal_id: { type: String },
    pingpong_id: { type: String },
    ebay_id: { type: String },
    etsy_id: { type: String },
    amazon_id: { type: String },
    shopee_id: { type: String },
    facebook_id: { type: String },
    tiktok_id: { type: String },
    list_view: { type: String },
    ebay_image_url: { type: String },
    ebay_history: { type: String },
    // List date

    ebaydate_delivery:{ type: String },
    ebaydate_start: { type: String },
    ebaydate_nextclass: { type: String },
    ebaydate_verify: { type: String },
    ebaydate_seller: { type: String },
    ebaydate_verifybank: { type: String },
    ebaydate_draft: { type: String },
    ebaydate_list1: { type: String },
    ebaydate_list2: { type: String },
    ebaydate_list3: { type: String },
    ebaydate_list4: { type: String },
    ebaydate_list5: { type: String },
    ebaydate_calendarseller: { type: String },
    ebaydate_calendarlist1: { type: String },
    ebaydate_calendarlist2: { type: String },
    ebaydate_calendarlist3: { type: String },
    ebaydate_calendarlist4: { type: String },
    ebaydate_calendarlist5: { type: String },
    ebaydate_suspended: { type: String },
    ebaydate_contact1: { type: String },
    ebaydate_contact2: { type: String },
    ebaydate_contact3: { type: String },
    ebaydate_contact4: { type: String },
    ebaydate_contact5: { type: String },
    ebaydate_checksus1: { type: String },
    ebaydate_checksus2: { type: String },
    ebaydate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Ebay", ebaySchema);
