import mongoose from "mongoose";
import Sim from "../models/sim";
const { ObjectId } = mongoose.Schema;

const etsySchema = mongoose.Schema(
  {
    etsy_id: { type: String, required: true },
    etsy_user: { type: String },
    etsy_password: { type: String },
    etsy_detail: { type: String },
    etsy_limit: { type: String },
    etsy_item: { type: String },
    etsy_sold: { type: String },
    etsy_feedback: { type: String },
    etsy_plan: { type: String },
    etsy_block: { type: String },
    etsy_error: { type: String },
    etsy_processing: { type: String },
    etsy_type: { type: String },
    etsy_sell_status: { type: String },
    etsy_owner: { type: String },
    etsy_employee: { type: String },
    etsy_outline: { type: String },
    etsy_status: { type: String },
    etsy_class: { type: String },
    etsy_support: { type: String },
    etsy_note: { type: String },
    //Liên kết field
    list_view: { type: String },
    device_id: { type: String, ref: "Device" },
    proxy_id:{ type: String, ref: "Proxy"},
    info_id: { type: String , ref: "Info"},
    mail_id: { type: ObjectId, ref: "Mail"},
    sim_id: { type: ObjectId, ref: "Sim" },
    bank_id: { type: ObjectId, ref: "Bank" },
    payoneer_id: { type: ObjectId, ref: "Payoneer"},
    paypal_id: { type: ObjectId, ref: "Paypal" },
    pingpong_id: {type: ObjectId, ref: "Pingpong" },
    ebay_id: {type: ObjectId, ref: "Ebay" },
    //etsy_id: { type: ObjectId, ref: "Etsy"},
    amazon_id: { type: ObjectId, ref: "Amazon"},
    shopee_id: { type: ObjectId, ref: "Shopee"},
    facebook_id: { type: ObjectId, ref: "Facebook"},
    tiktok_id: { type: ObjectId, ref: "Tiktok"},


    etsy_image_url: { type: String },
    etsy_history: { type: String },
    // List date
    etsydate_delivery: { type: String },
    etsydate_start: { type: String },
    etsydate_nextclass: { type: String },
    etsydate_verify: { type: String },
    etsydate_seller: { type: String },
    etsydate_verifybank: { type: String },
    etsydate_draft: { type: String },
    etsydate_list1: { type: String },
    etsydate_list2: { type: String },
    etsydate_list3: { type: String },
    etsydate_list4: { type: String },
    etsydate_list5: { type: String },
    etsydate_calendarseller: { type: String },
    etsydate_calendarlist1: { type: String },
    etsydate_calendarlist2: { type: String },
    etsydate_calendarlist3: { type: String },
    etsydate_calendarlist4: { type: String },
    etsydate_calendarlist5: { type: String },
    etsydate_moveroom: { type: String },
    etsydate_error: { type: String },
    etsydate_restrict: { type: String },
    etsydate_suspended: { type: String },
    etsydate_contact1: { type: String },
    etsydate_contact2: { type: String },
    etsydate_contact3: { type: String },
    etsydate_contact4: { type: String },
    etsydate_contact5: { type: String },
    etsydate_checksus1: { type: String },
    etsydate_checksus2: { type: String },
    etsydate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Etsy", etsySchema);
