import mongoose from "mongoose";

const etsySchema = mongoose.Schema(
  {
    etsy_id: { type: String, required: true },
    etsy_user: { type: String },
    etsy_password: { type: String },
    etsy_detail: { type: String },
    etsy_limit: { type: String,},
    etsy_item: { type: String },
    etsy_sold: { type: String },
    etsy_feedback: { type: String },
    etsy_plan: { type: String,default: "chrome"},
    etsy_processing: { type: String },
    etsy_type: { type: String },
    etsy_sell_status: { type: String },
    etsy_owner: { type: String },
    etsy_employee: { type: String, default: "Nguyễn Hoài" },
    etsy_outline: { type: String },
    etsy_status: { type: String },
    etsy_class: { type: String },
    etsy_support:{ type: String },
    etsy_note: { type: String },
    device_id: { type: String },
    proxy_id:{ type: String },
    info_id: { type: String },
    mail_id: { type: String },
    sim_id: { type: String },
    bank_id: { type: String },
    payoneer_id: { type: String },
    paypal_id: { type: String },
    pingpong_id: { type: String },
    ebay_id: { type: String },
    etsy_id: { type: String },
    amazon_id: { type: String },
    shopee_id: { type: String },
    facebook_id: { type: String },
    tiktok_id: { type: String },
    list_view: { type: String },
    etsy_image_url: { type: String },
    // List date
    etsydate_delivery:{ type: String },
    etsydate_start: { type: String },
    etsydate_nextclass: { type: String },
    etsydate_verify: { type: String },
    etsydate_seller: { type: String },
    etsydate_verifybank: { type: String },
    etsydate_draft: { type: String },
    etsydate_list1: { type: String },
    etsydate_list2: { type: String },
    etsydate_list3: { type: String },
    etsydate_list4: { type: String },
    etsydate_list5: { type: String },
    etsydate_expectedseller: { type: String },
    etsydate_expectedlist1: { type: String },
    etsydate_expectedlist2: { type: String },
    etsydate_expectedlist3: { type: String },
    etsydate_expectedlist4: { type: String },
    etsydate_expectedlist5: { type: String },
    etsydate_suspended: { type: String },
    etsydate_checksus1: { type: String },
    etsydate_contact1: { type: String },
    etsydate_contact2: { type: String },
    etsydate_contact3: { type: String },
    etsydate_contact4: { type: String },
    etsydate_contact5: { type: String },
    etsydate_checksus2: { type: String },
    etsydate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Etsy", etsySchema);
