import mongoose from "mongoose";
import Sim from "../models/sim";
const { ObjectId } = mongoose.Schema;

const facebookSchema = mongoose.Schema(
  {
    facebook_id: { type: String, required: true },
    facebook_user: { type: String },
    facebook_password: { type: String },
    facebook_detail: { type: String },
    facebook_limit: { type: String },
    facebook_item: { type: String },
    facebook_sold: { type: String },
    facebook_feedback: { type: String },
    facebook_plan: { type: String },
    facebook_block: { type: String },
    facebook_error: { type: String },
    facebook_processing: { type: String },
    facebook_type: { type: String },
    facebook_sell_status: { type: String },
    facebook_owner: { type: String },
    facebook_employee: { type: String },
    facebook_outline: { type: String },
    facebook_status: { type: String },
    facebook_class: { type: String },
    facebook_support: { type: String },
    facebook_note: { type: String },
    //Liên kết field
    list_view: { type: String },
    device_id: { type: String, ref: "Device" },
    proxy_id:{ type: String, ref: "Proxy"},
    info_id: { type: String , ref: "Info"},
    mail_id: { type: ObjectId, ref: "Mail"},
    sim_id: { type: ObjectId, ref: "Sim" },
    bank_id: { type: ObjectId, ref: "Bank" },
    payoneer_id: { type: ObjectId, ref: "Payoneer"},
    paypal_id: { type: ObjectId, ref: "Paypal" },
    pingpong_id: {type: ObjectId, ref: "Pingpong" },
    ebay_id: {type: ObjectId, ref: "Ebay" },
    etsy_id: { type: ObjectId, ref: "Etsy"},
    amazon_id: { type: ObjectId, ref: "Amazon"},
    shopee_id: { type: ObjectId, ref: "Shopee"},
    //facebook_id: { type: ObjectId, ref: "Facebook"},
    tiktok_id: { type: ObjectId, ref: "Tiktok"},


    facebook_image_url: { type: String },
    facebook_history: { type: String },
    // List date
    facebookdate_delivery: { type: String },
    facebookdate_start: { type: String },
    facebookdate_nextclass: { type: String },
    facebookdate_verify: { type: String },
    facebookdate_seller: { type: String },
    facebookdate_verifybank: { type: String },
    facebookdate_draft: { type: String },
    facebookdate_list1: { type: String },
    facebookdate_list2: { type: String },
    facebookdate_list3: { type: String },
    facebookdate_list4: { type: String },
    facebookdate_list5: { type: String },
    facebookdate_calendarseller: { type: String },
    facebookdate_calendarlist1: { type: String },
    facebookdate_calendarlist2: { type: String },
    facebookdate_calendarlist3: { type: String },
    facebookdate_calendarlist4: { type: String },
    facebookdate_calendarlist5: { type: String },
    facebookdate_moveroom: { type: String },
    facebookdate_error: { type: String },
    facebookdate_restrict: { type: String },
    facebookdate_suspended: { type: String },
    facebookdate_contact1: { type: String },
    facebookdate_contact2: { type: String },
    facebookdate_contact3: { type: String },
    facebookdate_contact4: { type: String },
    facebookdate_contact5: { type: String },
    facebookdate_checksus1: { type: String },
    facebookdate_checksus2: { type: String },
    facebookdate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Facebook", facebookSchema);
