import mongoose from "mongoose";

const facebookSchema = mongoose.Schema(
  {
    facebook_id: { type: String, required: true },
    facebook_user: { type: String },
    facebook_password: { type: String },
    facebook_detail: { type: String },
    facebook_limit: { type: String,},
    facebook_item: { type: String },
    facebook_sold: { type: String },
    facebook_feedback: { type: String },
    facebook_plan: { type: String,default: "chrome"},
    facebook_processing: { type: String },
    facebook_type: { type: String },
    facebook_sell_status: { type: String },
    facebook_owner: { type: String },
    facebook_employee: { type: String, default: "Nguyễn Hoài" },
    facebook_outline: { type: String },
    facebook_status: { type: String },
    facebook_class: { type: String },
    facebook_support:{ type: String },
    facebook_note: { type: String },
    device_id: { type: String },
    proxy_id:{ type: String },
    info_id: { type: String },
    mail_id: { type: String },
    sim_id: { type: String },
    bank_id: { type: String },
    payoneer_id: { type: String },
    paypal_id: { type: String },
    pingpong_id: { type: String },
    list_view: { type: String },
    facebook_image_url: { type: String },
    // List date
    facebookdate_delivery:{ type: String },
    facebookdate_start: { type: String },
    facebookdate_nextclass: { type: String },
    facebookdate_verify: { type: String },
    facebookdate_seller: { type: String },
    facebookdate_verifybank: { type: String },
    facebookdate_draft: { type: String },
    facebookdate_list1: { type: String },
    facebookdate_list2: { type: String },
    facebookdate_list3: { type: String },
    facebookdate_list4: { type: String },
    facebookdate_list5: { type: String },
    facebookdate_expectedseller: { type: String },
    facebookdate_expectedlist1: { type: String },
    facebookdate_expectedlist2: { type: String },
    facebookdate_expectedlist3: { type: String },
    facebookdate_expectedlist4: { type: String },
    facebookdate_expectedlist5: { type: String },
    facebookdate_suspended: { type: String },
    facebookdate_checksus1: { type: String },
    facebookdate_contact1: { type: String },
    facebookdate_contact2: { type: String },
    facebookdate_contact3: { type: String },
    facebookdate_contact4: { type: String },
    facebookdate_contact5: { type: String },
    facebookdate_checksus2: { type: String },
    facebookdate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Facebook", facebookSchema);
