import mongoose from "mongoose";

const mailSchema = mongoose.Schema(
  {
    mail_id: { type: String, required: true },
    mail_user: { type: String },
    mail_password: { type: String },
    mail_detail: { type: String },
    mail_limit: { type: String,},
    mail_item: { type: String },
    mail_sold: { type: String },
    mail_feedback: { type: String },
    mail_plan: { type: String,default: "chrome"},
    mail_processing: { type: String },
    mail_type: { type: String },
    mail_sell_status: { type: String },
    mail_owner: { type: String },
    mail_employee: { type: String, default: "Nguyễn Hoài" },
    mail_outline: { type: String },
    mail_status: { type: String },
    mail_class: { type: String },
    mail_support:{ type: String },
    mail_note: { type: String },
    device_id: { type: String },
    proxy_id:{ type: String },
    info_id: { type: String },
    mail_id: { type: String },
    sim_id: { type: String },
    bank_id: { type: String },
    payoneer_id: { type: String },
    paypal_id: { type: String },
    pingpong_id: { type: String },
    ebay_id: { type: String },
    etsy_id: { type: String },
    amazon_id: { type: String },
    shopee_id: { type: String },
    facebook_id: { type: String },
    tiktok_id: { type: String },
    list_view: { type: String },
    mail_image_url: { type: String },
    // List date
    maildate_delivery:{ type: String },
    maildate_start: { type: String },
    maildate_nextclass: { type: String },
    maildate_verify: { type: String },
    maildate_seller: { type: String },
    maildate_verifybank: { type: String },
    maildate_draft: { type: String },
    maildate_list1: { type: String },
    maildate_list2: { type: String },
    maildate_list3: { type: String },
    maildate_list4: { type: String },
    maildate_list5: { type: String },
    maildate_expectedseller: { type: String },
    maildate_expectedlist1: { type: String },
    maildate_expectedlist2: { type: String },
    maildate_expectedlist3: { type: String },
    maildate_expectedlist4: { type: String },
    maildate_expectedlist5: { type: String },
    maildate_suspended: { type: String },
    maildate_checksus1: { type: String },
    maildate_contact1: { type: String },
    maildate_contact2: { type: String },
    maildate_contact3: { type: String },
    maildate_contact4: { type: String },
    maildate_contact5: { type: String },
    maildate_checksus2: { type: String },
    maildate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Mail", mailSchema);