import mongoose from "mongoose";
import Sim from "../models/sim";
const { ObjectId } = mongoose.Schema;

const mailSchema = mongoose.Schema(
  {
    mail_id: { type: String, required: true },
    mail_user: { type: String },
    mail_password: { type: String },
    mail_detail: { type: String },
    mail_limit: { type: String },
    mail_item: { type: String },
    mail_sold: { type: String },
    mail_feedback: { type: String },
    mail_plan: { type: String },
    mail_block: { type: String },
    mail_error: { type: String },
    mail_processing: { type: String },
    mail_type: { type: String },
    mail_sell_status: { type: String },
    mail_owner: { type: String },
    mail_employee: { type: String },
    mail_outline: { type: String },
    mail_status: { type: String },
    mail_class: { type: String },
    mail_support: { type: String },
    mail_note: { type: String },
    //Liên kết field
    list_view: { type: String },
    device_id: { type: String, ref: "Device" },
    proxy_id:{ type: String, ref: "Proxy"},
    info_id: { type: String , ref: "Info"},
    //mail_id: { type: ObjectId, ref: "Mail"},
    sim_id: { type: ObjectId, ref: "Sim" },
    bank_id: { type: ObjectId, ref: "Bank" },
    payoneer_id: { type: ObjectId, ref: "Payoneer"},
    paypal_id: { type: ObjectId, ref: "Paypal" },
    pingpong_id: {type: ObjectId, ref: "Pingpong" },
    ebay_id: {type: ObjectId, ref: "Ebay" },
    etsy_id: { type: ObjectId, ref: "Etsy"},
    amazon_id: { type: ObjectId, ref: "Amazon"},
    shopee_id: { type: ObjectId, ref: "Shopee"},
    facebook_id: { type: ObjectId, ref: "Facebook"},
    tiktok_id: { type: ObjectId, ref: "Tiktok"},


    mail_image_url: { type: String },
    mail_history: { type: String },
    // List date
    maildate_delivery: { type: String },
    maildate_start: { type: String },
    maildate_nextclass: { type: String },
    maildate_verify: { type: String },
    maildate_seller: { type: String },
    maildate_verifybank: { type: String },
    maildate_draft: { type: String },
    maildate_list1: { type: String },
    maildate_list2: { type: String },
    maildate_list3: { type: String },
    maildate_list4: { type: String },
    maildate_list5: { type: String },
    maildate_calendarseller: { type: String },
    maildate_calendarlist1: { type: String },
    maildate_calendarlist2: { type: String },
    maildate_calendarlist3: { type: String },
    maildate_calendarlist4: { type: String },
    maildate_calendarlist5: { type: String },
    maildate_moveroom: { type: String },
    maildate_error: { type: String },
    maildate_restrict: { type: String },
    maildate_suspended: { type: String },
    maildate_contact1: { type: String },
    maildate_contact2: { type: String },
    maildate_contact3: { type: String },
    maildate_contact4: { type: String },
    maildate_contact5: { type: String },
    maildate_checksus1: { type: String },
    maildate_checksus2: { type: String },
    maildate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Mail", mailSchema);
