import mongoose from "mongoose";
import Sim from "../models/sim";
const { ObjectId } = mongoose.Schema;

const payoneerSchema = mongoose.Schema(
  {
    payoneer_id: { type: String, required: true },
    payoneer_user: { type: String },
    payoneer_password: { type: String },
    payoneer_detail: { type: String },
    payoneer_limit: { type: String },
    payoneer_item: { type: String },
    payoneer_sold: { type: String },
    payoneer_feedback: { type: String },
    payoneer_plan: { type: String },
    payoneer_block: { type: String },
    payoneer_error: { type: String },
    payoneer_processing: { type: String },
    payoneer_type: { type: String },
    payoneer_sell_status: { type: String },
    payoneer_owner: { type: String },
    payoneer_employee: { type: String },
    payoneer_outline: { type: String },
    payoneer_status: { type: String },
    payoneer_class: { type: String },
    payoneer_support: { type: String },
    payoneer_note: { type: String },
    //Liên kết field
    list_view: { type: String },
    device_id: { type: String, ref: "Device" },
    proxy_id:{ type: String, ref: "Proxy"},
    info_id: { type: String , ref: "Info"},
    mail_id: { type: ObjectId, ref: "Mail"},
    sim_id: { type: ObjectId, ref: "Sim" },
    bank_id: { type: ObjectId, ref: "Bank" },
    //payoneer_id: { type: ObjectId, ref: "Payoneer"},
    paypal_id: { type: ObjectId, ref: "Paypal" },
    pingpong_id: {type: ObjectId, ref: "Pingpong" },
    ebay_id: {type: ObjectId, ref: "Ebay" },
    etsy_id: { type: ObjectId, ref: "Etsy"},
    amazon_id: { type: ObjectId, ref: "Amazon"},
    shopee_id: { type: ObjectId, ref: "Shopee"},
    facebook_id: { type: ObjectId, ref: "Facebook"},
    tiktok_id: { type: ObjectId, ref: "Tiktok"},


    payoneer_image_url: { type: String },
    payoneer_history: { type: String },
    // List date
    payoneerdate_delivery: { type: String },
    payoneerdate_start: { type: String },
    payoneerdate_nextclass: { type: String },
    payoneerdate_verify: { type: String },
    payoneerdate_seller: { type: String },
    payoneerdate_verifybank: { type: String },
    payoneerdate_draft: { type: String },
    payoneerdate_list1: { type: String },
    payoneerdate_list2: { type: String },
    payoneerdate_list3: { type: String },
    payoneerdate_list4: { type: String },
    payoneerdate_list5: { type: String },
    payoneerdate_calendarseller: { type: String },
    payoneerdate_calendarlist1: { type: String },
    payoneerdate_calendarlist2: { type: String },
    payoneerdate_calendarlist3: { type: String },
    payoneerdate_calendarlist4: { type: String },
    payoneerdate_calendarlist5: { type: String },
    payoneerdate_moveroom: { type: String },
    payoneerdate_error: { type: String },
    payoneerdate_restrict: { type: String },
    payoneerdate_suspended: { type: String },
    payoneerdate_contact1: { type: String },
    payoneerdate_contact2: { type: String },
    payoneerdate_contact3: { type: String },
    payoneerdate_contact4: { type: String },
    payoneerdate_contact5: { type: String },
    payoneerdate_checksus1: { type: String },
    payoneerdate_checksus2: { type: String },
    payoneerdate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Payoneer", payoneerSchema);
