import mongoose from "mongoose";

const payoneerSchema = mongoose.Schema(
  {
    payoneer_id: { type: String, required: true },
    payoneer_user: { type: String },
    payoneer_password: { type: String },
    payoneer_detail: { type: String },
    payoneer_limit: { type: String,},
    payoneer_item: { type: String },
    payoneer_sold: { type: String },
    payoneer_feedback: { type: String },
    payoneer_plan: { type: String,default: "chrome"},
    payoneer_processing: { type: String },
    payoneer_type: { type: String },
    payoneer_sell_status: { type: String },
    payoneer_owner: { type: String },
    payoneer_employee: { type: String, default: "Nguyễn Hoài" },
    payoneer_outline: { type: String },
    payoneer_status: { type: String },
    payoneer_class: { type: String },
    payoneer_support:{ type: String },
    payoneer_note: { type: String },
    device_id: { type: String },
    proxy_id:{ type: String },
    info_id: { type: String },
    mail_id: { type: String },
    sim_id: { type: String },
    bank_id: { type: String },
    payoneer_id: { type: String },
    paypal_id: { type: String },
    pingpong_id: { type: String },
    ebay_id: { type: String },
    etsy_id: { type: String },
    amazon_id: { type: String },
    shopee_id: { type: String },
    facebook_id: { type: String },
    tiktok_id: { type: String },
    list_view: { type: String },
    payoneer_image_url: { type: String },
    // List date
    payoneerdate_delivery:{ type: String },
    payoneerdate_start: { type: String },
    payoneerdate_nextclass: { type: String },
    payoneerdate_verify: { type: String },
    payoneerdate_seller: { type: String },
    payoneerdate_verifybank: { type: String },
    payoneerdate_draft: { type: String },
    payoneerdate_list1: { type: String },
    payoneerdate_list2: { type: String },
    payoneerdate_list3: { type: String },
    payoneerdate_list4: { type: String },
    payoneerdate_list5: { type: String },
    payoneerdate_expectedseller: { type: String },
    payoneerdate_expectedlist1: { type: String },
    payoneerdate_expectedlist2: { type: String },
    payoneerdate_expectedlist3: { type: String },
    payoneerdate_expectedlist4: { type: String },
    payoneerdate_expectedlist5: { type: String },
    payoneerdate_suspended: { type: String },
    payoneerdate_checksus1: { type: String },
    payoneerdate_contact1: { type: String },
    payoneerdate_contact2: { type: String },
    payoneerdate_contact3: { type: String },
    payoneerdate_contact4: { type: String },
    payoneerdate_contact5: { type: String },
    payoneerdate_checksus2: { type: String },
    payoneerdate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Payoneer", payoneerSchema);
