import mongoose from "mongoose";
import Sim from "../models/sim";
const { ObjectId } = mongoose.Schema;

const paypalSchema = mongoose.Schema(
  {
    paypal_id: { type: String, required: true },
    paypal_user: { type: String },
    paypal_password: { type: String },
    paypal_detail: { type: String },
    paypal_limit: { type: String },
    paypal_item: { type: String },
    paypal_sold: { type: String },
    paypal_feedback: { type: String },
    paypal_plan: { type: String },
    paypal_block: { type: String },
    paypal_error: { type: String },
    paypal_processing: { type: String },
    paypal_type: { type: String },
    paypal_sell_status: { type: String },
    paypal_owner: { type: String },
    paypal_employee: { type: String },
    paypal_outline: { type: String },
    paypal_status: { type: String },
    paypal_class: { type: String },
    paypal_support: { type: String },
    paypal_note: { type: String },
    //Liên kết field
    list_view: { type: String },
    device_id: { type: String, ref: "Device" },
    proxy_id:{ type: String, ref: "Proxy"},
    info_id: { type: String , ref: "Info"},
    mail_id: { type: ObjectId, ref: "Mail"},
    sim_id: { type: ObjectId, ref: "Sim" },
    bank_id: { type: ObjectId, ref: "Bank" },
    payoneer_id: { type: ObjectId, ref: "Payoneer"},
    //paypal_id: { type: ObjectId, ref: "Paypal" },
    pingpong_id: {type: ObjectId, ref: "Pingpong" },
    ebay_id: {type: ObjectId, ref: "Ebay" },
    etsy_id: { type: ObjectId, ref: "Etsy"},
    amazon_id: { type: ObjectId, ref: "Amazon"},
    shopee_id: { type: ObjectId, ref: "Shopee"},
    facebook_id: { type: ObjectId, ref: "Facebook"},
    tiktok_id: { type: ObjectId, ref: "Tiktok"},


    paypal_image_url: { type: String },
    paypal_history: { type: String },
    // List date
    paypaldate_delivery: { type: String },
    paypaldate_start: { type: String },
    paypaldate_nextclass: { type: String },
    paypaldate_verify: { type: String },
    paypaldate_seller: { type: String },
    paypaldate_verifybank: { type: String },
    paypaldate_draft: { type: String },
    paypaldate_list1: { type: String },
    paypaldate_list2: { type: String },
    paypaldate_list3: { type: String },
    paypaldate_list4: { type: String },
    paypaldate_list5: { type: String },
    paypaldate_calendarseller: { type: String },
    paypaldate_calendarlist1: { type: String },
    paypaldate_calendarlist2: { type: String },
    paypaldate_calendarlist3: { type: String },
    paypaldate_calendarlist4: { type: String },
    paypaldate_calendarlist5: { type: String },
    paypaldate_moveroom: { type: String },
    paypaldate_error: { type: String },
    paypaldate_restrict: { type: String },
    paypaldate_suspended: { type: String },
    paypaldate_contact1: { type: String },
    paypaldate_contact2: { type: String },
    paypaldate_contact3: { type: String },
    paypaldate_contact4: { type: String },
    paypaldate_contact5: { type: String },
    paypaldate_checksus1: { type: String },
    paypaldate_checksus2: { type: String },
    paypaldate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Paypal", paypalSchema);
