import mongoose from "mongoose";

const paypalSchema = mongoose.Schema(
  {
    paypal_id: { type: String, required: true },
    paypal_user: { type: String },
    paypal_password: { type: String },
    paypal_detail: { type: String },
    paypal_limit: { type: String,},
    paypal_item: { type: String },
    paypal_sold: { type: String },
    paypal_feedback: { type: String },
    paypal_plan: { type: String,default: "chrome"},
    paypal_processing: { type: String },
    paypal_type: { type: String },
    paypal_sell_status: { type: String },
    paypal_owner: { type: String },
    paypal_employee: { type: String, default: "Nguyễn Hoài" },
    paypal_outline: { type: String },
    paypal_status: { type: String },
    paypal_class: { type: String },
    paypal_support:{ type: String },
    paypal_note: { type: String },
    device_id: { type: String },
    proxy_id:{ type: String },
    info_id: { type: String },
    mail_id: { type: String },
    sim_id: { type: String },
    bank_id: { type: String },
    payoneer_id: { type: String },
    paypal_id: { type: String },
    pingpong_id: { type: String },
    ebay_id: { type: String },
    etsy_id: { type: String },
    amazon_id: { type: String },
    shopee_id: { type: String },
    facebook_id: { type: String },
    tiktok_id: { type: String },
    list_view: { type: String },
    paypal_image_url: { type: String },
    // List date
    paypaldate_delivery:{ type: String },
    paypaldate_start: { type: String },
    paypaldate_nextclass: { type: String },
    paypaldate_verify: { type: String },
    paypaldate_seller: { type: String },
    paypaldate_verifybank: { type: String },
    paypaldate_draft: { type: String },
    paypaldate_list1: { type: String },
    paypaldate_list2: { type: String },
    paypaldate_list3: { type: String },
    paypaldate_list4: { type: String },
    paypaldate_list5: { type: String },
    paypaldate_expectedseller: { type: String },
    paypaldate_expectedlist1: { type: String },
    paypaldate_expectedlist2: { type: String },
    paypaldate_expectedlist3: { type: String },
    paypaldate_expectedlist4: { type: String },
    paypaldate_expectedlist5: { type: String },
    paypaldate_suspended: { type: String },
    paypaldate_checksus1: { type: String },
    paypaldate_contact1: { type: String },
    paypaldate_contact2: { type: String },
    paypaldate_contact3: { type: String },
    paypaldate_contact4: { type: String },
    paypaldate_contact5: { type: String },
    paypaldate_checksus2: { type: String },
    paypaldate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Paypal", paypalSchema);