import mongoose from "mongoose";
import Sim from "../models/sim";
const { ObjectId } = mongoose.Schema;

const pingpongSchema = mongoose.Schema(
  {
    pingpong_id: { type: String, required: true },
    pingpong_user: { type: String },
    pingpong_password: { type: String },
    pingpong_detail: { type: String },
    pingpong_limit: { type: String },
    pingpong_item: { type: String },
    pingpong_sold: { type: String },
    pingpong_feedback: { type: String },
    pingpong_plan: { type: String },
    pingpong_block: { type: String },
    pingpong_error: { type: String },
    pingpong_processing: { type: String },
    pingpong_type: { type: String },
    pingpong_sell_status: { type: String },
    pingpong_owner: { type: String },
    pingpong_employee: { type: String },
    pingpong_outline: { type: String },
    pingpong_status: { type: String },
    pingpong_class: { type: String },
    pingpong_support: { type: String },
    pingpong_note: { type: String },
    //Liên kết field
    list_view: { type: String },
    device_id: { type: String, ref: "Device" },
    proxy_id:{ type: String, ref: "Proxy"},
    info_id: { type: String , ref: "Info"},
    mail_id: { type: ObjectId, ref: "Mail"},
    sim_id: { type: ObjectId, ref: "Sim" },
    bank_id: { type: ObjectId, ref: "Bank" },
    payoneer_id: { type: ObjectId, ref: "Payoneer"},
    paypal_id: { type: ObjectId, ref: "Paypal" },
    //pingpong_id: {type: ObjectId, ref: "Pingpong" },
    ebay_id: {type: ObjectId, ref: "Ebay" },
    etsy_id: { type: ObjectId, ref: "Etsy"},
    amazon_id: { type: ObjectId, ref: "Amazon"},
    shopee_id: { type: ObjectId, ref: "Shopee"},
    facebook_id: { type: ObjectId, ref: "Facebook"},
    tiktok_id: { type: ObjectId, ref: "Tiktok"},


    pingpong_image_url: { type: String },
    pingpong_history: { type: String },
    // List date
    pingpongdate_delivery: { type: String },
    pingpongdate_start: { type: String },
    pingpongdate_nextclass: { type: String },
    pingpongdate_verify: { type: String },
    pingpongdate_seller: { type: String },
    pingpongdate_verifybank: { type: String },
    pingpongdate_draft: { type: String },
    pingpongdate_list1: { type: String },
    pingpongdate_list2: { type: String },
    pingpongdate_list3: { type: String },
    pingpongdate_list4: { type: String },
    pingpongdate_list5: { type: String },
    pingpongdate_calendarseller: { type: String },
    pingpongdate_calendarlist1: { type: String },
    pingpongdate_calendarlist2: { type: String },
    pingpongdate_calendarlist3: { type: String },
    pingpongdate_calendarlist4: { type: String },
    pingpongdate_calendarlist5: { type: String },
    pingpongdate_moveroom: { type: String },
    pingpongdate_error: { type: String },
    pingpongdate_restrict: { type: String },
    pingpongdate_suspended: { type: String },
    pingpongdate_contact1: { type: String },
    pingpongdate_contact2: { type: String },
    pingpongdate_contact3: { type: String },
    pingpongdate_contact4: { type: String },
    pingpongdate_contact5: { type: String },
    pingpongdate_checksus1: { type: String },
    pingpongdate_checksus2: { type: String },
    pingpongdate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Pingpong", pingpongSchema);
