import mongoose from "mongoose";

const pingpongSchema = mongoose.Schema(
  {
    pingpong_id: { type: String, required: true },
    pingpong_user: { type: String },
    pingpong_password: { type: String },
    pingpong_detail: { type: String },
    pingpong_limit: { type: String,},
    pingpong_item: { type: String },
    pingpong_sold: { type: String },
    pingpong_feedback: { type: String },
    pingpong_plan: { type: String,default: "chrome"},
    pingpong_processing: { type: String },
    pingpong_type: { type: String },
    pingpong_sell_status: { type: String },
    pingpong_owner: { type: String },
    pingpong_employee: { type: String, default: "Nguyễn Hoài" },
    pingpong_outline: { type: String },
    pingpong_status: { type: String },
    pingpong_class: { type: String },
    pingpong_support:{ type: String },
    pingpong_note: { type: String },
    device_id: { type: String },
    proxy_id:{ type: String },
    info_id: { type: String },
    mail_id: { type: String },
    sim_id: { type: String },
    bank_id: { type: String },
    payoneer_id: { type: String },
    pingpong_id: { type: String },
    pingpong_id: { type: String },
    ebay_id: { type: String },
    etsy_id: { type: String },
    amazon_id: { type: String },
    shopee_id: { type: String },
    facebook_id: { type: String },
    tiktok_id: { type: String },
    list_view: { type: String },
    pingpong_image_url: { type: String },
    // List date
    pingpongdate_delivery:{ type: String },
    pingpongdate_start: { type: String },
    pingpongdate_nextclass: { type: String },
    pingpongdate_verify: { type: String },
    pingpongdate_seller: { type: String },
    pingpongdate_verifybank: { type: String },
    pingpongdate_draft: { type: String },
    pingpongdate_list1: { type: String },
    pingpongdate_list2: { type: String },
    pingpongdate_list3: { type: String },
    pingpongdate_list4: { type: String },
    pingpongdate_list5: { type: String },
    pingpongdate_expectedseller: { type: String },
    pingpongdate_expectedlist1: { type: String },
    pingpongdate_expectedlist2: { type: String },
    pingpongdate_expectedlist3: { type: String },
    pingpongdate_expectedlist4: { type: String },
    pingpongdate_expectedlist5: { type: String },
    pingpongdate_suspended: { type: String },
    pingpongdate_checksus1: { type: String },
    pingpongdate_contact1: { type: String },
    pingpongdate_contact2: { type: String },
    pingpongdate_contact3: { type: String },
    pingpongdate_contact4: { type: String },
    pingpongdate_contact5: { type: String },
    pingpongdate_checksus2: { type: String },
    pingpongdate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Pingpong", pingpongSchema);