import mongoose from "mongoose";
import Sim from "../models/sim";
const { ObjectId } = mongoose.Schema;

const proxySchema = mongoose.Schema(
  {
    proxy_id: { type: String, required: true },
    proxy_user: { type: String },
    proxy_password: { type: String },
    proxy_detail: { type: String },
    proxy_limit: { type: String },
    proxy_item: { type: String },
    proxy_sold: { type: String },
    proxy_feedback: { type: String },
    proxy_plan: { type: String },
    proxy_block: { type: String },
    proxy_error: { type: String },
    proxy_processing: { type: String },
    proxy_type: { type: String },
    proxy_sell_status: { type: String },
    proxy_owner: { type: String },
    proxy_employee: { type: String },
    proxy_outline: { type: String },
    proxy_status: { type: String },
    proxy_class: { type: String },
    proxy_support: { type: String },
    proxy_note: { type: String },
    //Liên kết field
    list_view: { type: String },
    device_id: { type: String, ref: "Device" },
    //proxy_id:{ type: String, ref: "Proxy"},
    info_id: { type: String , ref: "Info"},
    mail_id: { type: ObjectId, ref: "Mail"},
    sim_id: { type: ObjectId, ref: "Sim" },
    bank_id: { type: ObjectId, ref: "Bank" },
    payoneer_id: { type: ObjectId, ref: "Payoneer"},
    paypal_id: { type: ObjectId, ref: "Paypal" },
    pingpong_id: {type: ObjectId, ref: "Pingpong" },
    ebay_id: {type: ObjectId, ref: "Ebay" },
    etsy_id: { type: ObjectId, ref: "Etsy"},
    amazon_id: { type: ObjectId, ref: "Amazon"},
    shopee_id: { type: ObjectId, ref: "Shopee"},
    facebook_id: { type: ObjectId, ref: "Facebook"},
    tiktok_id: { type: ObjectId, ref: "Tiktok"},


    proxy_image_url: { type: String },
    proxy_history: { type: String },
    // List date
    proxydate_delivery: { type: String },
    proxydate_start: { type: String },
    proxydate_nextclass: { type: String },
    proxydate_verify: { type: String },
    proxydate_seller: { type: String },
    proxydate_verifybank: { type: String },
    proxydate_draft: { type: String },
    proxydate_list1: { type: String },
    proxydate_list2: { type: String },
    proxydate_list3: { type: String },
    proxydate_list4: { type: String },
    proxydate_list5: { type: String },
    proxydate_calendarseller: { type: String },
    proxydate_calendarlist1: { type: String },
    proxydate_calendarlist2: { type: String },
    proxydate_calendarlist3: { type: String },
    proxydate_calendarlist4: { type: String },
    proxydate_calendarlist5: { type: String },
    proxydate_moveroom: { type: String },
    proxydate_error: { type: String },
    proxydate_restrict: { type: String },
    proxydate_suspended: { type: String },
    proxydate_contact1: { type: String },
    proxydate_contact2: { type: String },
    proxydate_contact3: { type: String },
    proxydate_contact4: { type: String },
    proxydate_contact5: { type: String },
    proxydate_checksus1: { type: String },
    proxydate_checksus2: { type: String },
    proxydate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Proxy", proxySchema);
