import mongoose from "mongoose";
import Sim from "../models/sim";

const shopeeSchema = mongoose.Schema(
  {
    shopee_id: { type: String, required: true },
    shopee_user: { type: String },
    shopee_password: { type: String },
    shopee_detail: { type: String },
    shopee_limit: { type: String,},
    shopee_item: { type: String },
    shopee_sold: { type: String },
    shopee_feedback: { type: String },
    shopee_plan: { type: String},
    shopee_block: { type: String},
    shopee_error: { type: String},
    shopee_processing: { type: String },
    shopee_type: { type: String },
    shopee_sell_status: { type: String },
    shopee_owner: { type: String },
    shopee_employee: { type: String },
    shopee_outline: { type: String },
    shopee_status: { type: String },
    shopee_class: { type: String },
    shopee_support:{ type: String },
    shopee_note: { type: String },
    device_id: { type: String },
    proxy_id:{ type: String },
    info_id: { type: String },
    mail_id: { type: String },
    sim_id: { type: String },
    bank_id: { type: String },
    payoneer_id: { type: String },
    paypal_id: { type: String },
    pingpong_id: { type: String },
    shopee_id: { type: String },
    etsy_id: { type: String },
    amazon_id: { type: String },
    shopee_id: { type: String },
    facebook_id: { type: String },
    tiktok_id: { type: String },
    list_view: { type: String },
    shopee_image_url: { type: String },
    // List date

    shopeedate_delivery:{ type: String },
    shopeedate_start: { type: String },
    shopeedate_nextclass: { type: String },
    shopeedate_verify: { type: String },
    shopeedate_seller: { type: String },
    shopeedate_verifybank: { type: String },
    shopeedate_draft: { type: String },
    shopeedate_list1: { type: String },
    shopeedate_list2: { type: String },
    shopeedate_list3: { type: String },
    shopeedate_list4: { type: String },
    shopeedate_list5: { type: String },
    shopeedate_calendarseller: { type: String },
    shopeedate_calendarlist1: { type: String },
    shopeedate_calendarlist2: { type: String },
    shopeedate_calendarlist3: { type: String },
    shopeedate_calendarlist4: { type: String },
    shopeedate_calendarlist5: { type: String },
    shopeedate_suspended: { type: String },
    shopeedate_contact1: { type: String },
    shopeedate_contact2: { type: String },
    shopeedate_contact3: { type: String },
    shopeedate_contact4: { type: String },
    shopeedate_contact5: { type: String },
    shopeedate_checksus1: { type: String },
    shopeedate_checksus2: { type: String },
    shopeedate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Shopee", shopeeSchema);
