import mongoose from "mongoose";
import Sim from "../models/sim";
const { ObjectId } = mongoose.Schema;

const simSchema = mongoose.Schema(
  {
    sim_id: { type: String, required: true },
    sim_user: { type: String },
    sim_password: { type: String },
    sim_detail: { type: String },
    sim_limit: { type: String },
    sim_item: { type: String },
    sim_sold: { type: String },
    sim_feedback: { type: String },
    sim_plan: { type: String },
    sim_block: { type: String },
    sim_error: { type: String },
    sim_processing: { type: String },
    sim_type: { type: String },
    sim_sell_status: { type: String },
    sim_owner: { type: String },
    sim_employee: { type: String },
    sim_outline: { type: String },
    sim_status: { type: String },
    sim_class: { type: String },
    sim_support: { type: String },
    sim_note: { type: String },
    //Liên kết field
    list_view: { type: String },
    device_id: { type: String, ref: "Device" },
    proxy_id:{ type: String, ref: "Proxy"},
    info_id: { type: String , ref: "Info"},
    mail_id: { type: ObjectId, ref: "Mail"},
    //sim_id: { type: ObjectId, ref: "Sim" },
    bank_id: { type: ObjectId, ref: "Bank" },
    payoneer_id: { type: ObjectId, ref: "Payoneer"},
    paypal_id: { type: ObjectId, ref: "Paypal" },
    pingpong_id: {type: ObjectId, ref: "Pingpong" },
    ebay_id: {type: ObjectId, ref: "Ebay" },
    etsy_id: { type: ObjectId, ref: "Etsy"},
    amazon_id: { type: ObjectId, ref: "Amazon"},
    shopee_id: { type: ObjectId, ref: "Shopee"},
    facebook_id: { type: ObjectId, ref: "Facebook"},
    tiktok_id: { type: ObjectId, ref: "Tiktok"},

    sim_image_url: { type: String },
    sim_history: { type: String },
    // List date
    simdate_delivery: { type: String },
    simdate_start: { type: String },
    simdate_nextclass: { type: String },
    simdate_verify: { type: String },
    simdate_seller: { type: String },
    simdate_verifybank: { type: String },
    simdate_draft: { type: String },
    simdate_list1: { type: String },
    simdate_list2: { type: String },
    simdate_list3: { type: String },
    simdate_list4: { type: String },
    simdate_list5: { type: String },
    simdate_calendarseller: { type: String },
    simdate_calendarlist1: { type: String },
    simdate_calendarlist2: { type: String },
    simdate_calendarlist3: { type: String },
    simdate_calendarlist4: { type: String },
    simdate_calendarlist5: { type: String },
    simdate_moveroom: { type: String },
    simdate_error: { type: String },
    simdate_restrict: { type: String },
    simdate_suspended: { type: String },
    simdate_contact1: { type: String },
    simdate_contact2: { type: String },
    simdate_contact3: { type: String },
    simdate_contact4: { type: String },
    simdate_contact5: { type: String },
    simdate_checksus1: { type: String },
    simdate_checksus2: { type: String },
    simdate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Sim", simSchema);
