import mongoose from "mongoose";

const simSchema = mongoose.Schema(
  {
    sim_id: { type: String, required: true },
    sim_user: { type: String },
    sim_password: { type: String },
    sim_detail: { type: String },
    sim_limit: { type: String,},
    sim_item: { type: String },
    sim_sold: { type: String },
    sim_feedback: { type: String },
    sim_plan: { type: String,default: "chrome"},
    sim_processing: { type: String },
    sim_type: { type: String },
    sim_sell_status: { type: String },
    sim_owner: { type: String },
    sim_employee: { type: String, default: "Nguyễn Hoài" },
    sim_outline: { type: String },
    sim_status: { type: String },
    sim_class: { type: String },
    sim_support:{ type: String },
    sim_note: { type: String },
    device_id: { type: String },
    proxy_id:{ type: String },
    info_id: { type: String },
    mail_id: { type: String },
    sim_id: { type: String },
    bank_id: { type: String },
    payoneer_id: { type: String },
    paypal_id: { type: String },
    pingpong_id: { type: String },
    ebay_id: { type: String },
    etsy_id: { type: String },
    amazon_id: { type: String },
    shopee_id: { type: String },
    facebook_id: { type: String },
    tiktok_id: { type: String },
    list_view: { type: String },
    sim_image_url: { type: String },
    // List date
    simdate_delivery:{ type: String },
    simdate_start: { type: String },
    simdate_nextclass: { type: String },
    simdate_verify: { type: String },
    simdate_seller: { type: String },
    simdate_verifybank: { type: String },
    simdate_draft: { type: String },
    simdate_list1: { type: String },
    simdate_list2: { type: String },
    simdate_list3: { type: String },
    simdate_list4: { type: String },
    simdate_list5: { type: String },
    simdate_expectedseller: { type: String },
    simdate_expectedlist1: { type: String },
    simdate_expectedlist2: { type: String },
    simdate_expectedlist3: { type: String },
    simdate_expectedlist4: { type: String },
    simdate_expectedlist5: { type: String },
    simdate_suspended: { type: String },
    simdate_checksus1: { type: String },
    simdate_contact1: { type: String },
    simdate_contact2: { type: String },
    simdate_contact3: { type: String },
    simdate_contact4: { type: String },
    simdate_contact5: { type: String },
    simdate_checksus2: { type: String },
    simdate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Sim", simSchema);
