import mongoose from "mongoose";

const tiktokSchema = mongoose.Schema(
  {
    tiktok_id: { type: String, required: true },
    tiktok_user: { type: String },
    tiktok_password: { type: String },
    tiktok_detail: { type: String },
    tiktok_limit: { type: String,},
    tiktok_item: { type: String },
    tiktok_sold: { type: String },
    tiktok_feedback: { type: String },
    tiktok_plan: { type: String,default: "chrome"},
    tiktok_processing: { type: String },
    tiktok_type: { type: String },
    tiktok_sell_status: { type: String },
    tiktok_owner: { type: String },
    tiktok_employee: { type: String, default: "Nguyễn Hoài" },
    tiktok_outline: { type: String },
    tiktok_status: { type: String },
    tiktok_class: { type: String },
    tiktok_support:{ type: String },
    tiktok_note: { type: String },
    device_id: { type: String },
    proxy_id:{ type: String },
    info_id: { type: String },
    mail_id: { type: String },
    sim_id: { type: String },
    bank_id: { type: String },
    payoneer_id: { type: String },
    paypal_id: { type: String },
    pingpong_id: { type: String },
    ebay_id: { type: String },
    etsy_id: { type: String },
    amazon_id: { type: String },
    shopee_id: { type: String },
    facebook_id: { type: String },
    tiktok_id: { type: String },
    list_view: { type: String },
    tiktok_image_url: { type: String },
    // List date
    tiktokdate_delivery:{ type: String },
    tiktokdate_start: { type: String },
    tiktokdate_nextclass: { type: String },
    tiktokdate_verify: { type: String },
    tiktokdate_seller: { type: String },
    tiktokdate_verifybank: { type: String },
    tiktokdate_draft: { type: String },
    tiktokdate_list1: { type: String },
    tiktokdate_list2: { type: String },
    tiktokdate_list3: { type: String },
    tiktokdate_list4: { type: String },
    tiktokdate_list5: { type: String },
    tiktokdate_expectedseller: { type: String },
    tiktokdate_expectedlist1: { type: String },
    tiktokdate_expectedlist2: { type: String },
    tiktokdate_expectedlist3: { type: String },
    tiktokdate_expectedlist4: { type: String },
    tiktokdate_expectedlist5: { type: String },
    tiktokdate_suspended: { type: String },
    tiktokdate_checksus1: { type: String },
    tiktokdate_contact1: { type: String },
    tiktokdate_contact2: { type: String },
    tiktokdate_contact3: { type: String },
    tiktokdate_contact4: { type: String },
    tiktokdate_contact5: { type: String },
    tiktokdate_checksus2: { type: String },
    tiktokdate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Tiktok", tiktokSchema);
