import mongoose from "mongoose";
import Sim from "../models/sim";
const { ObjectId } = mongoose.Schema;

const tiktokSchema = mongoose.Schema(
  {
    tiktok_id: { type: String, required: true },
    tiktok_user: { type: String },
    tiktok_password: { type: String },
    tiktok_detail: { type: String },
    tiktok_limit: { type: String },
    tiktok_item: { type: String },
    tiktok_sold: { type: String },
    tiktok_feedback: { type: String },
    tiktok_plan: { type: String },
    tiktok_block: { type: String },
    tiktok_error: { type: String },
    tiktok_processing: { type: String },
    tiktok_type: { type: String },
    tiktok_sell_status: { type: String },
    tiktok_owner: { type: String },
    tiktok_employee: { type: String },
    tiktok_outline: { type: String },
    tiktok_status: { type: String },
    tiktok_class: { type: String },
    tiktok_support: { type: String },
    tiktok_note: { type: String },
    //Liên kết field
    list_view: { type: String },
    device_id: { type: String, ref: "Device" },
    proxy_id:{ type: String, ref: "Proxy"},
    info_id: { type: String , ref: "Info"},
    mail_id: { type: ObjectId, ref: "Mail"},
    sim_id: { type: ObjectId, ref: "Sim" },
    bank_id: { type: ObjectId, ref: "Bank" },
    payoneer_id: { type: ObjectId, ref: "Payoneer"},
    paypal_id: { type: ObjectId, ref: "Paypal" },
    pingpong_id: {type: ObjectId, ref: "Pingpong" },
    ebay_id: {type: ObjectId, ref: "Ebay" },
    etsy_id: { type: ObjectId, ref: "Etsy"},
    amazon_id: { type: ObjectId, ref: "Amazon"},
    shopee_id: { type: ObjectId, ref: "Shopee"},
    facebook_id: { type: ObjectId, ref: "Facebook"},
    //tiktok_id: { type: ObjectId, ref: "Tiktok"},


    tiktok_image_url: { type: String },
    tiktok_history: { type: String },
    // List date
    tiktokdate_delivery: { type: String },
    tiktokdate_start: { type: String },
    tiktokdate_nextclass: { type: String },
    tiktokdate_verify: { type: String },
    tiktokdate_seller: { type: String },
    tiktokdate_verifybank: { type: String },
    tiktokdate_draft: { type: String },
    tiktokdate_list1: { type: String },
    tiktokdate_list2: { type: String },
    tiktokdate_list3: { type: String },
    tiktokdate_list4: { type: String },
    tiktokdate_list5: { type: String },
    tiktokdate_calendarseller: { type: String },
    tiktokdate_calendarlist1: { type: String },
    tiktokdate_calendarlist2: { type: String },
    tiktokdate_calendarlist3: { type: String },
    tiktokdate_calendarlist4: { type: String },
    tiktokdate_calendarlist5: { type: String },
    tiktokdate_moveroom: { type: String },
    tiktokdate_error: { type: String },
    tiktokdate_restrict: { type: String },
    tiktokdate_suspended: { type: String },
    tiktokdate_contact1: { type: String },
    tiktokdate_contact2: { type: String },
    tiktokdate_contact3: { type: String },
    tiktokdate_contact4: { type: String },
    tiktokdate_contact5: { type: String },
    tiktokdate_checksus1: { type: String },
    tiktokdate_checksus2: { type: String },
    tiktokdate_checksus3: { type: String },
  },
  { timeStamps: true }
);

module.exports = mongoose.model("Tiktok", tiktokSchema);
